name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub (or your container registry)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: xeost/get-static-website:latest
          platforms: linux/amd64

      # Deploy to remote server
    #   - name: Deploy to Server
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       port: ${{ secrets.SERVER_PORT }}
    #       script: |
    #         # Stop and remove existing container if it exists
    #         docker stop your-app-name || true
    #         docker rm your-app-name || true
            
    #         # Pull new image
    #         docker pull yourusername/your-app-name:latest
            
    #         # Run new container
    #         docker run -d \
    #           --name your-app-name \
    #           -p 8000:8000 \
    #           yourusername/your-app-name:latest